# shellcheck shell=bash disable=SC2034
# Migrate legacy module-owned PVE notification objects to operator ownership.
# This fragment is sourced by run-migrations.sh and must remain side-effect free.

MIGRATION_TARGET_VERSION=0.7.0
MIGRATION_FILES=(
    "${PVE_TOOLBOX_CONF_DIR:-/etc/pve-toolbox}/native-notifications.conf"
    "${PVE_TOOLBOX_STATE_DIR:-/var/lib/pve-toolbox}/native-notifications.state"
)
MIGRATION_UNITS=()

_m010_error() {
    printf 'pve-toolbox: native notification migration: %s\n' "$1" >&2
}

_m010_safe_file() {
    local path=$1 private=$2 mode
    [[ -f $path && ! -L $path ]] || return 1
    [[ $(stat -c '%u' "$path") -eq $EUID ]] || return 1
    mode=$(stat -c '%a' "$path")
    if [[ $private -eq 1 ]]; then
        (( (8#$mode & 077) == 0 ))
    else
        (( (8#$mode & 022) == 0 ))
    fi
}

_m010_read_legacy_identity() (
    local conf=$1 state=$2
    unset NT_KIND NT_TARGET_NAME NT_MATCHER_NAME
    unset TARGET_TYPE TARGET_NAME MATCHER_NAME ASSET_SUM
    # These files are generated by pve-toolbox as shell-quoted assignments.
    # Source them only after verifying their type, owner, and write permissions.
    # shellcheck source=/dev/null
    source "$conf"
    # shellcheck source=/dev/null
    source "$state"
    printf '%s\0' "${NT_KIND:-}" "${NT_TARGET_NAME:-}" "${NT_MATCHER_NAME:-}" \
        "${TARGET_TYPE:-}" "${TARGET_NAME:-}" "${MATCHER_NAME:-}" "${ASSET_SUM:-}"
)

_m010_asset_sum() {
    local helper=$1 template_dir=$2 file
    local -a templates=(
        pve-toolbox-subject.txt.hbs
        pve-toolbox-body.txt.hbs
        pve-toolbox-body.html.hbs
    )
    [[ -f $helper && ! -L $helper ]] || return 1
    for file in "${templates[@]}"; do
        [[ -f $template_dir/$file && ! -L $template_dir/$file ]] || return 1
    done
    {
        sha256sum "$helper"
        for file in "${templates[@]}"; do
            sha256sum "$template_dir/$file"
        done
    } | sha256sum | awk '{print $1}'
}

_m010_get_json() {
    local path=$1
    pvesh get "$path" --output-format json 2>/dev/null
}

migration_apply() {
    local conf state api_type endpoint matcher installed_sum
    local target_path matcher_path helper legacy_helper template_dir file
    local NT_KIND NT_TARGET_NAME NT_MATCHER_NAME
    local TARGET_TYPE TARGET_NAME MATCHER_NAME ASSET_SUM
    local marker='managed by pve-toolbox/native-notifications'
    local -a identity=()
    local -a templates=(
        pve-toolbox-subject.txt.hbs
        pve-toolbox-body.txt.hbs
        pve-toolbox-body.html.hbs
    )

    conf="${PVE_TOOLBOX_CONF_DIR}/native-notifications.conf"
    state="${PVE_TOOLBOX_STATE_DIR}/native-notifications.state"
    helper=${PVE_TOOLBOX_NATIVE_NOTIFY_BIN:-/usr/bin/pve-toolbox-native-notify}
    legacy_helper=${PVE_TOOLBOX_LEGACY_NATIVE_NOTIFY_BIN:-/usr/local/bin/pve-toolbox-native-notify}
    template_dir=${PVE_TOOLBOX_NOTIFICATION_TEMPLATE_DIR:-/etc/pve/notification-templates/default}

    if [[ ! -e $conf && ! -e $state ]]; then
        return 0
    fi
    if [[ ! -e $conf || ! -e $state ]]; then
        _m010_error "legacy config and state are incomplete; restore both files or remove the orphan after reviewing the PVE target"
        return 1
    fi
    _m010_safe_file "$conf" 1 && _m010_safe_file "$state" 0 || {
        _m010_error "legacy config or state is not a protected regular file; correct its ownership and permissions before retrying"
        return 1
    }
    mapfile -d '' -t identity < <(_m010_read_legacy_identity "$conf" "$state")
    [[ ${#identity[@]} -eq 7 ]] || {
        _m010_error "could not read the legacy ownership identity; restore the last known-good toolbox config and retry"
        return 1
    }
    NT_KIND=${identity[0]}
    NT_TARGET_NAME=${identity[1]}
    NT_MATCHER_NAME=${identity[2]}
    TARGET_TYPE=${identity[3]}
    TARGET_NAME=${identity[4]}
    MATCHER_NAME=${identity[5]}
    ASSET_SUM=${identity[6]}

    case ${NT_KIND:-} in
        discord|webhook) api_type=webhook ;;
        gotify|smtp) api_type=$NT_KIND ;;
        *)
            _m010_error "unsupported legacy endpoint kind '${NT_KIND:-missing}'; no notification objects were changed"
            return 1
            ;;
    esac
    [[ ${NT_TARGET_NAME:-} =~ ^pve-toolbox-[A-Za-z0-9._-]+$ \
        && ${NT_MATCHER_NAME:-} =~ ^pve-toolbox-[A-Za-z0-9._-]+$ ]] || {
        _m010_error "legacy target or matcher name is invalid; no notification objects were changed"
        return 1
    }
    [[ ${TARGET_TYPE:-} == "$api_type" \
        && ${TARGET_NAME:-} == "$NT_TARGET_NAME" \
        && ${MATCHER_NAME:-} == "$NT_MATCHER_NAME" \
        && ${ASSET_SUM:-} =~ ^[0-9a-f]{64}$ ]] || {
        _m010_error "recorded ownership does not match the configured endpoint identity; inspect the PVE target and legacy state before retrying"
        return 1
    }

    command -v pvesh >/dev/null 2>&1 && command -v jq >/dev/null 2>&1 \
        && command -v sha256sum >/dev/null 2>&1 || {
        _m010_error "pvesh, jq, and sha256sum are required; install the missing host tools and retry"
        return 1
    }
    [[ -x $helper && -f $helper && ! -L $helper ]] || {
        _m010_error "the package-owned custom-event sender is missing or unsafe; reinstall pve-toolbox and retry"
        return 1
    }
    [[ -x $legacy_helper && -f $legacy_helper && ! -L $legacy_helper ]] || {
        _m010_error "the legacy custom-event sender is missing or unsafe; restore the module assets and retry"
        return 1
    }
    for file in "${templates[@]}"; do
        [[ -f $template_dir/$file && ! -L $template_dir/$file ]] || {
            _m010_error "notification template '$file' is missing or unsafe; restore the module assets and retry"
            return 1
        }
    done
    installed_sum=$(_m010_asset_sum "$legacy_helper" "$template_dir") || {
        _m010_error "could not verify the legacy notification assets"
        return 1
    }
    [[ $installed_sum == "$ASSET_SUM" ]] || {
        _m010_error "legacy notification assets do not match their ownership record; no notification objects were changed"
        return 1
    }

    target_path="/cluster/notifications/endpoints/$api_type/$NT_TARGET_NAME"
    matcher_path="/cluster/notifications/matchers/$NT_MATCHER_NAME"
    endpoint=$(_m010_get_json "$target_path") || {
        _m010_error "PVE target '$NT_TARGET_NAME' is missing or unreadable; restore it or remove the stale toolbox config before retrying"
        return 1
    }
    matcher=$(_m010_get_json "$matcher_path") || {
        _m010_error "PVE matcher '$NT_MATCHER_NAME' is missing or unreadable; restore it or remove the stale toolbox config before retrying"
        return 1
    }
    jq -e --arg name "$NT_TARGET_NAME" --arg marker "$marker" \
        'type == "object" and .name == $name and .comment == $marker' \
        <<<"$endpoint" >/dev/null || {
        _m010_error "PVE target '$NT_TARGET_NAME' is foreign or ambiguous; its ownership marker was not changed"
        return 1
    }
    jq -e --arg name "$NT_MATCHER_NAME" --arg target "$NT_TARGET_NAME" --arg marker "$marker" \
        'type == "object" and .name == $name and .comment == $marker
         and (.target | type == "array" and index($target) != null)' \
        <<<"$matcher" >/dev/null || {
        _m010_error "PVE matcher '$NT_MATCHER_NAME' is foreign or no longer routes to '$NT_TARGET_NAME'; no notification objects were changed"
        return 1
    }

    pvesh create "/cluster/notifications/targets/$NT_TARGET_NAME/test" \
        >/dev/null 2>&1 || {
        _m010_error "PVE test delivery for '$NT_TARGET_NAME' failed; legacy ownership was preserved"
        return 1
    }
    "$helper" notice 'pve-toolbox migration' \
        'Custom notification delivery remains available after the package upgrade.' \
        >/dev/null 2>&1 || {
        _m010_error "the package-owned custom-event sender failed; legacy ownership was preserved"
        return 1
    }

    # PVE already owns the target, matcher, templates, and protected credentials.
    # Retiring these two toolbox files transfers future management to PVE without
    # rewriting any native notification field.
    rm -f -- "$conf" "$state"
}
